/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MODEL;

import VIEW.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Huu Dat
 */
public class ThayDoiQuyDinh extends javax.swing.JFrame {

    /**
     * Creates new form ThayDoiQuyDinh
     */
    public ThayDoiQuyDinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbTDQD = new javax.swing.JLabel();
        lbTTLP = new javax.swing.JLabel();
        lbMaLoaiPhong = new javax.swing.JLabel();
        lbTenLoaiPhong = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        lbTTLK = new javax.swing.JLabel();
        lbMaLoaiKhach = new javax.swing.JLabel();
        lbHSLoaiKhach = new javax.swing.JLabel();
        bThem = new javax.swing.JButton();
        bSua = new javax.swing.JButton();
        bXoa = new javax.swing.JButton();
        bThem1 = new javax.swing.JButton();
        bSua1 = new javax.swing.JButton();
        bXoa1 = new javax.swing.JButton();
        lbTTQD = new javax.swing.JLabel();
        lbSLKhachToiDa = new javax.swing.JLabel();
        lbTLPhuThu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bCapNhat = new javax.swing.JButton();
        bThoat = new javax.swing.JButton();
        txtMaLoaiPhong = new javax.swing.JTextField();
        txtTenLoaiPhong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtMaLoaiKhach = new javax.swing.JTextField();
        txtHSLoaiKhach = new javax.swing.JTextField();
        txtTLPhuThu = new javax.swing.JTextField();
        txtSLKhachToiDa = new javax.swing.JTextField();
        rbKND = new javax.swing.JRadioButton();
        rdKNN = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTDQD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTDQD.setForeground(new java.awt.Color(51, 0, 255));
        lbTDQD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTDQD.setText("Thay Đổi Quy Định");

        lbTTLP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTTLP.setForeground(new java.awt.Color(204, 0, 153));
        lbTTLP.setText("Thông tin loại phòng");

        lbMaLoaiPhong.setText("Mã loại phòng");

        lbTenLoaiPhong.setText("Tên loại phòng");

        lbDonGia.setText("Đơn giá");

        lbTTLK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTTLK.setForeground(new java.awt.Color(204, 0, 153));
        lbTTLK.setText("Thông tin loại khách");

        lbMaLoaiKhach.setText("Mã loại khách");

        lbHSLoaiKhach.setText("Hệ số loại khách");

        bThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/svn_added.png"))); // NOI18N
        bThem.setText("Thêm");
        bThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThemActionPerformed(evt);
            }
        });

        bSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixed.png"))); // NOI18N
        bSua.setText("Sửa");
        bSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuaActionPerformed(evt);
            }
        });

        bXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/svn_deleted.png"))); // NOI18N
        bXoa.setText("Xóa");
        bXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXoaActionPerformed(evt);
            }
        });

        bThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/svn_added.png"))); // NOI18N
        bThem1.setText("Thêm");
        bThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThem1ActionPerformed(evt);
            }
        });

        bSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixed.png"))); // NOI18N
        bSua1.setText("Sửa");
        bSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSua1ActionPerformed(evt);
            }
        });

        bXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/svn_deleted.png"))); // NOI18N
        bXoa1.setText("Xóa");
        bXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXoa1ActionPerformed(evt);
            }
        });

        lbTTQD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTTQD.setForeground(new java.awt.Color(204, 0, 204));
        lbTTQD.setText("Thông tin quy định");

        lbSLKhachToiDa.setText("Số lượng khách tối đa");

        lbTLPhuThu.setText("Tỉ lệ phụ thu");

        jLabel13.setText("%");

        bCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_39.gif"))); // NOI18N
        bCapNhat.setText("Cập nhật");
        bCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCapNhatActionPerformed(evt);
            }
        });

        bThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_23.gif"))); // NOI18N
        bThoat.setText("Thoát");
        bThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThoatActionPerformed(evt);
            }
        });

        txtMaLoaiKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLoaiKhachActionPerformed(evt);
            }
        });

        rbKND.setText("Khách nội địa");

        rdKNN.setText("Khách nước ngoài");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTTLP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMaLoaiKhach)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTTLK))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTTQD)
                        .addGap(0, 444, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbSLKhachToiDa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSLKhachToiDa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaLoaiPhong)
                                    .addComponent(lbTenLoaiPhong)
                                    .addComponent(lbDonGia))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenLoaiPhong, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaLoaiPhong)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bXoa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bThem1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSua1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bXoa1)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbKND)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdKNN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbHSLoaiKhach)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHSLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bCapNhat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTLPhuThu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTLPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))
                                .addGap(33, 33, 33))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTDQD)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(bThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbTDQD)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTTLP)
                    .addComponent(lbTTLK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaLoaiPhong)
                    .addComponent(lbMaLoaiKhach)
                    .addComponent(txtMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenLoaiPhong)
                    .addComponent(txtTenLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbKND)
                    .addComponent(rdKNN))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHSLoaiKhach)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHSLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDonGia)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bThem)
                    .addComponent(bSua)
                    .addComponent(bXoa)
                    .addComponent(bSua1)
                    .addComponent(bXoa1)
                    .addComponent(bThem1))
                .addGap(20, 20, 20)
                .addComponent(lbTTQD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLKhachToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSLKhachToiDa)
                    .addComponent(lbTLPhuThu)
                    .addComponent(txtTLPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCapNhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThemActionPerformed
        // TODO add your handling code here:
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement ("insert into LOAIPHONG values(?,?,?)");
            ps.setString(1, txtMaLoaiPhong.getText());
            ps.setString(2, txtTenLoaiPhong.getText());
            ps.setString(3, txtDonGia.getText());
            int chk = ps.executeUpdate();
            if(chk>0){
                JOptionPane.showMessageDialog(this,"Thêm Thành Công");
            }
            else{
                JOptionPane.showMessageDialog(this,"Thêm Thất Bại");
                        }
        }catch(Exception ex){
            System.out.println(ex.toString());
            }
    }//GEN-LAST:event_bThemActionPerformed

    private void bSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuaActionPerformed
        // TODO add your handling code here:
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pre = conn.prepareStatement ("Update LOAIPHONG set TenLoaiPhong=?,DonGia=? where MaLoaiPhong=?");
            pre.setString(1, txtTenLoaiPhong.getText());
            pre.setString(2, txtDonGia.getText());
            pre.executeUpdate();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_bSuaActionPerformed

    private void bXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXoaActionPerformed
        // TODO add your handling code here:
        try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pre = conn.prepareStatement("delete LOAIPHONG where MaLoaiPhong=?,TenLoaiPhong=?,DonGia=?");
            if(JOptionPane.showConfirmDialog(this,"Xác Nhận Xóa?","Ðồng Ý",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                pre.executeUpdate();
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_bXoaActionPerformed

    private void bThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThoatActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bThoatActionPerformed

    private void bThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThem1ActionPerformed
        // TODO add your handling code here:
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps1 = conn.prepareStatement ("insert into LOAIKHACH values(?,?,?)");
            ps1.setString(1, txtMaLoaiKhach.getText());
            if(rbKND.isSelected()){
                ps1.setBoolean(2, true);
            }
            else
            {
                ps1.setBoolean(2, false);
            }
           
            ps1.setString(3, txtHSLoaiKhach.getText());
            int chk = ps1.executeUpdate();
            if(chk>0){
                JOptionPane.showMessageDialog(this,"Thêm Thành Công");
            }
            else{
                JOptionPane.showMessageDialog(this,"Thêm Thất Bại");
                        }
        }catch(Exception ex){
            System.out.println(ex.toString());
            }                      
    }//GEN-LAST:event_bThem1ActionPerformed

    private void bSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSua1ActionPerformed
        // TODO add your handling code here:
          try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pre = conn.prepareStatement ("Update LOAIKHACH set MaLoaiKhach=?,HeSoLoaiKhach=? where MaLoaiKhach=?");
            pre.setString(1, txtMaLoaiKhach.getText());
            pre.setString(2, txtHSLoaiKhach.getText());
            pre.executeUpdate();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_bSua1ActionPerformed

    private void bXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXoa1ActionPerformed
        // TODO add your handling code here:
         try {
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement pre = conn.prepareStatement("delete LOAIKHACH where MaLoaiKhach=?,TenLoaiKhach=?,HeSoLoaiKhach=?");
            if(JOptionPane.showConfirmDialog(this,"Xác Nhận Xóa?","Ðồng Ý",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                pre.executeUpdate();
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_bXoa1ActionPerformed

    private void txtMaLoaiKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLoaiKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiKhachActionPerformed

    private void bCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCapNhatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThayDoiQuyDinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ThayDoiQuyDinh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCapNhat;
    private javax.swing.JButton bSua;
    private javax.swing.JButton bSua1;
    private javax.swing.JButton bThem;
    private javax.swing.JButton bThem1;
    private javax.swing.JButton bThoat;
    private javax.swing.JButton bXoa;
    private javax.swing.JButton bXoa1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbHSLoaiKhach;
    private javax.swing.JLabel lbMaLoaiKhach;
    private javax.swing.JLabel lbMaLoaiPhong;
    private javax.swing.JLabel lbSLKhachToiDa;
    private javax.swing.JLabel lbTDQD;
    private javax.swing.JLabel lbTLPhuThu;
    private javax.swing.JLabel lbTTLK;
    private javax.swing.JLabel lbTTLP;
    private javax.swing.JLabel lbTTQD;
    private javax.swing.JLabel lbTenLoaiPhong;
    private javax.swing.JRadioButton rbKND;
    private javax.swing.JRadioButton rdKNN;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHSLoaiKhach;
    private javax.swing.JTextField txtMaLoaiKhach;
    private javax.swing.JTextField txtMaLoaiPhong;
    private javax.swing.JTextField txtSLKhachToiDa;
    private javax.swing.JTextField txtTLPhuThu;
    private javax.swing.JTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
